### ISSUE TITLE
Persist shard sinces are not advanced after environmentd restart

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#13916]
### What version of Materialize are you using?

v0.26.1-dev (d625f21f8)

### How did you install Materialize?

Built from source

### What is the issue?

Restarting environmentd seems to break the correct advancing of `since`s of storage collection persist shards.

To reproduce:

1. Instrument Materialize to print shard IDs of storage collections. For example [here](https://github.com/MaterializeInc/materialize/blob/main/src/storage/src/controller.rs#L602).
2. Run `bin/environmentd --reset`.
3. Use the logged shard IDs to connect directly to the shards using `mz-persist-client` and observe their `since` updates.
    * https://github.com/teskje/persist-test can be used for that. Just clone it and run (with adjusted paths):
      ```
      cargo run --bin monitor-since -- 'postgres://<user>@%2Ftmp?options=--search_path=consensus' 'file:///Users/<user>/devel/materialize/mzdata/persist/blob' '<shard-id>'
      ```
4. Observe that the shard `since`s tick along nicely.
5. Ctrl+c environmentd.
6. Run `bin/environmentd`.
7. Check the `since`s of the persist shards again. Observe how they are not advancing anymore.

My limited debugging revealed that the storage controller actually attempts to periodically downgrade the `since`s even after the environmentd restart. You can verify that by adding some logging [here](https://github.com/MaterializeInc/materialize/blob/c9f1254632e02f39fcadb2613d0b0ad962327ab2/src/storage/src/controller.rs#L918). There must be other `ReadHandle`s somewhere that hold back the shard `since`s. Or maybe the ones from the previous environmentd run are not cleaned up correctly.

**Comment by danhhz** [comment]
> Or maybe the ones from the previous environmentd run are not cleaned up correctly.

Ah yeah, this is exactly it! They are leased, but actually writing the expiry task is a TODO. (Coming up soon as part of stuff @pH14 is working on.)

**Comment by danhhz** [comment]
This should also maybe be fixed by https://github.com/MaterializeInc/materialize/pull/13922

**Comment by teskje** [comment]
I just tested with the latest main and unfortunately I still don't see the sinces advancing after a restart.

**Comment by pH14** [comment]
Mm it might not have run for long enough. Dan's PR conservatively takes 15min for a reader to expire after its last heartbeat.

**Comment by teskje** [comment]
Ah, that would definitely explain it! I didn't wait nearly as long.

**Comment by teskje** [comment]
I tested it with a one-minute expiry timeout and that works, so I'm satisfied!
