### ISSUE TITLE
persist, envd: PersistCompactionWorker leaks

### ISSUE THREAD

**Issue by lluki** [MaterializeInc/materialize#15828]
### What version of Materialize are you using?

v0.30.0-dev

### How did you install Materialize?

Built from source

### What is the issue?

As part of investigating #15354: The `PersistCompactionWorker` tokio task never terminates, leading to an ever increasing memory consumption. 

Repro
====

Add a print statement at the beginning and end of PersistCompactionWorker (src/persist-client/src/internal/compact.rs:108). Then repeat the following commands

```
psql> CREATE TABLE t1 (f1 int);
psql> DROP TABLE t1;
```

and observe the task never gets removed.

Thoughts
====
I'm unfortunately not very familiar with this code, but I think the bug might not actually be in PersistCompactionWorker. Rather the actual bug is that we keep the Compactor struct around forever.

The same problem might also exist with materialized views, sinks, sources etc. but I have not yet verified this.

**Comment by lluki** [comment]
Might be a duplicate of #15704, I suggest waiting until we fixed that and then check it again.

**Comment by uce** [comment]
> Might be a duplicate of https://github.com/MaterializeInc/materialize/issues/15704, I suggest waiting until we fixed that and then check it again.

Yes, let's do that!

**Comment by vmarcos** [comment]
This is just a quick note that the leak in issue #15704 is fixed by PR https://github.com/MaterializeInc/materialize/pull/15862; however, I'm keeping the issue open until I get around to adding a regression test to ensure the leak stays fixed. So if a solution to #15704 was blocking this work item, it might be a good time now to pick it up again.

**Comment by lluki** [comment]
Retested on environmentd v0.33.0-dev (5dfb03b9ce57a68aa9161ca188befbe62e713006) the issue is still present. The tasks

 * `PersistCompactionWorker`
 * `persist::heartbeat_write`
 * `PersistGcWorker`

do not get cleaned up. After creating and dropping 200 tables, there are around 800 tasks pending. After a fresh environmentd startup, we have around 150 tasks, so 200 tables created a surplus of 650 tasks.

**Comment by vmarcos** [comment]
We observed in [this Slack discussion](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1669640075056749?thread_ts=1669636038.135849&cid=C02PPB50ZHS) that the same tasks leak in `computed`. This could explain the behavior observed in https://github.com/MaterializeInc/materialize/issues/15354#issuecomment-1326549677.

**Comment by aljoscha** [comment]
fyi @danhhz & @pH14, this looks like a source of the remaining seqno hold issues

**Comment by pH14** [comment]
Not familiar with the `computed` side, but I'd imagine in `envd` these leaked tasks come from `PersistWriteHandles`... I don't believe it drops `WriteHandle`s that have advanced to `[]`. We might want a similar trick as were added for `SinceHandles`: https://github.com/MaterializeInc/materialize/blob/b2751bb71c852a7f3cce16bb9640bf7e5b96c44f/src/storage-client/src/controller.rs#L1866-L1893

That said, I'm not sure these are specifically responsible for the seqno leaks we're seeing on prod. Since we see seqnos drift up immediately after restarts, I'm not sure it's due to dropped collections

**Comment by dseisun-materialize** [comment]
@pH14 doing some backlog cleaning. Before I dig in here, do you know if this ever got resolved/is still an issue?

**Comment by benesch** [comment]
Calling this closed. If the task is indeed still leaking, it's not causing any observable problems.
