### ISSUE TITLE
`SHOW CLUSTER REPLICAS` takes 2+ minutes

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#16161]
### What version of Materialize are you using?

 v0.32.0 (b04623960)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

```
materialize=> show cluster replicas;
     cluster      | replica |  size   | ready 
------------------+---------+---------+-------
 c2               | r1      | 2xsmall | t
 c2               | r2      | xsmall  | t
 default          | r1      | 2xsmall | t
 mz_introspection | r1      | 2xsmall | t
 mz_system        | r1      | 2xsmall | t
(5 rows)

Time: 129378.174 ms (02:09.378)
```

I spun up a new cluster with two replicas -- one `2xsmall` and one `xsmall` and `SHOW CLUSTER REPLICAS` takes over 2 minutes to run.  If I switch to the `mz_introspection` cluster it's fast:

```
materialize=> set cluster = mz_introspection;
SET
Time: 42.181 ms
materialize=> show cluster replicas;
     cluster      | replica |  size   | ready 
------------------+---------+---------+-------
 c2               | r1      | 2xsmall | t
 c2               | r2      | xsmall  | t
 default          | r1      | 2xsmall | t
 mz_introspection | r1      | 2xsmall | t
 mz_system        | r1      | 2xsmall | t
(5 rows)

Time: 288.793 ms
materialize=> 
```

**Comment by benesch** [comment]
Is it slow on both clusters? Can you show the output of `EXPLAIN TIMESTAMP FOR SHOW CLUSTER REPLICAS` on one of the slow clusters?

**Comment by heeringa** [comment]
It's only slow on `c2` 

```
materialize=> explain timestamp for show cluster replicas;
                              Timestamp                              
---------------------------------------------------------------------
           query timestamp: 1668824872068 (2022-11-19 02:27:52.068) +
                     since:[1668824871000 (2022-11-19 02:27:51.000)]+
                     upper:[1668824872069 (2022-11-19 02:27:52.069)]+
          global timestamp: 1668824872068 (2022-11-19 02:27:52.068) +
   can respond immediately: true                                    +
                                                                    +
 source mz_catalog.mz_clusters (s285, storage):                     +
             read frontier:[1668824871000 (2022-11-19 02:27:51.000)]+
            write frontier:[1668824872069 (2022-11-19 02:27:52.069)]+
                                                                    +
 source mz_catalog.mz_cluster_replicas (s289, storage):             +
             read frontier:[1668824871000 (2022-11-19 02:27:51.000)]+
            write frontier:[1668824872069 (2022-11-19 02:27:52.069)]+
                                                                    +
 source mz_internal.mz_cluster_replica_statuses (s290, storage):    +
             read frontier:[1668824871000 (2022-11-19 02:27:51.000)]+
            write frontier:[1668824872069 (2022-11-19 02:27:52.069)]+
 
(1 row)

Time: 41.734 ms
```

**Comment by heeringa** [comment]
☝️ that was on `c2` by the way

**Comment by aljoscha** [comment]
This smells like #16090 which has been fixed but not released yet

**Comment by benesch** [comment]
This actually looks like #15937 to me! The shard for `mz_cluster_replicas` is sdd771d8e which has a huge seqno leak:

![image](https://user-images.githubusercontent.com/882976/202969562-11e8f497-2155-493c-8d22-a93e626cf1aa.png)

I just (at 12:01am) power cycled all of Brent's cluster replicas. If, at 12:16am, all the seqnos come down, and `SHOW CLUSTER REPLICAS` is again fast, we'll know that it's #15937. Note that we expect the seqno leak to be fixed in v0.32.2, dropping this Wednesday! 🤞🏽

**Comment by benesch** [comment]
Still not fast. Not sure what to make of that. I'll try again in the morning, I guess.

**Comment by aljoscha** [comment]
I was thinking #16090 because Brent mentioned that the query is fast on the introspection cluster. Could also be sth completely different, of course!

**Comment by benesch** [comment]
The affected cluster is tiny though! One `2xsmall` replica and one `xsmall` replica. I'd expect latencies of a second or two if this were #16090, but instead it's taking two minutes (!!). I just retested this morning, and it's still taking 2m. Even though persist looks healthy. No leaked seqnos, and a relatively small consensus table in Cockroach.

**Comment by benesch** [comment]
On Brent's environment, `SELECT * FROM mz_cluster_replicas` is faster than ever.

But `SELECT * FROM mz_internal.mz_cluster_replica_statuses` is massively slow. 2+ minutes. 

So that rules out anything about join planning, I think. There is something that goes wrong, really wrong, with the `mz_cluster_replica_statuses` table.

**Comment by benesch** [comment]
This is the affected shard ID: environment-dd6ece12-3ef2-4a11-9a5d-d5e7350c3334/s64c0548f-a76d-4f7a-94d5-3f8b61d78ee5

Here's a dump of its consensus state: https://gist.github.com/benesch/ae87715c07cacff2448835ad02799964

There are 4000+ batch parts. Almost _all_ of those batch parts seem to be from before October 24, judging by the `since`/`upper` timestamps.

If I had to guess, it seems like we piled up tons and tons of state in this shard back when compaction didn't work correctly, and we're now unable to correct that. Compaction seems to be working well now, as we only have a few batch parts from the present day.

**Comment by benesch** [comment]
Also: is it right that we don't fetch batch parts in parallel in the `persist_source`? Reading some code, and it seems like only compaction fetches batch parts in parallel?

**Comment by benesch** [comment]
The only way I think of to repair Brent and Frank's environments, and the customer environments from this era that I'm sure are affected too, is to build https://github.com/MaterializeInc/cloud/issues/4477.

**Comment by benesch** [comment]
💡The reason we haven't noticed this until now is because, until #15934 went into v0.31.0 two weeks ago, `SHOW CLUSTER REPLICAS` didn't touch `mz_cluster_replica_statuses`. It just looked at `mz_cluster_replicas`. So `mz_cluster_replica_statuses` has been b0rked on this regions for many many weeks, but no one was looking at it.

**Comment by aljoscha** [comment]
> Also: is it right that we don't fetch batch parts in parallel in the `persist_source`? Reading some code, and it seems like only compaction fetches batch parts in parallel?

Yes and no, if you have a multi-worker timely cluster, we spread the work of fetching across all timely workers, but a single timely worker will not set off requests for multiple parts concurrently. Making a note!

**Comment by pH14** [comment]
@benesch your assessment checks out to me. We both don't prefetch parts in `persist_source` and it looks like that shard hasn't been compacted back down yet, so it's going to be slooooooow. This won't be the first or last time we want something like https://github.com/MaterializeInc/cloud/issues/4477 so this might be the forcing function to make it happen

**Comment by heeringa** [comment]
@pH14 and @benesch Checking in on this bug - would you all like me to keep my environment around to test the forced-compaction fix via CLI when we get around to it, or is it okay for me to blow some stuff away?

**Comment by benesch** [comment]
Would love to keep your `mz_cluster_replica_statuses` shard in place, but that's not something you can blow away! You should feel free to drop replicas/sources to your heart's content.

**Comment by benesch** [comment]
Welp. `SHOW CLUSTER REPLICAS` is once again fast in your env, Brent, but not because of the compaction tool we built. v0.34 has a system table migration in it that uses a new persist shard, so the old shard with the piled up state is no longer referenced by your env.

**Comment by pH14** [comment]
@benesch @heeringa are we comfortable closing this one out? The slowness was almost certainly from the batch part growth, which 1) should no longer happen on new shards (post Oct/Nov compaction fixes) 2) is fixable with our one-off compaction tool for any shards that grew large pre compaction fixes

**Comment by benesch** [comment]
I was waiting on you to sign off! Yes, quite comfortable!
