### ISSUE TITLE
Column names from `SELECT` clause should be available to `GROUP BY`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#1673]
In Postgres it's possible to group by a renamed column, or a column whose name is only generated in the return set of a `SELECT` clause. However, @ruchirK and I struggled to get this to work today.

<hr/>

For example, this works in Postgres:

```
CREATE TABLE t (t TEXT, i INT);

INSERT INTO t VALUES
('abab', 1), 
('abab', 2), 
('acac', 1);

SELECT 
    substr(t, 0, 3) as val, 
    sum(i)
FROM t 
GROUP BY val;
```

Running a similar query in Materialize returned an error that there was no column named `val`.

@ruchirK Once your protobuf load gen lands and I can start working on the docs, I'll amend this issue to include more thorough repro steps.

**Comment by rjnn** [comment]
@cuongdo do we have the resources to invest in such a tech-debt paydown in 0.2? Otherwise 0.3 should be fine.

**Comment by cuongdo** [comment]
@benesch will this be addressed by your current set of name resolution changes?

**Comment by benesch** [comment]
I'm expecting it to become easily accomplishable with the name resolution work! But I'm not considering it part of the name resolution work proper.

**Comment by PeteJodo** [comment]
hey I don't mean to encroach or anything but I've been checking out materialize and noticed this issue is still listed under [Known Limitations](https://materialize.com/docs/known-limitations/#syntax--semantics) even though it looks to have been fixed last July. Not sure if that has something to do with how you release or whatever but figured I'd mention it in case it was an oversight

**Comment by benesch** [comment]
Not encroaching at all! It is an oversight. Thanks for pointing it out.
