### ISSUE TITLE
regression: WMR query hangs with no CPU activity (after being converted to a delta join?)

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#18759]
### What version of Materialize are you using?

c464ed645516aa66f7c2511d4a88abe591bd867c

### How did you install Materialize?

Docker image

### What is the issue?

After this commit:

```
commit c464ed645516aa66f7c2511d4a88abe591bd867c (HEAD)
Author: Gabor Gevay <gabor@materialize.com>
Date:   Mon Apr 3 12:49:52 2023 +0200

    Mark ReductionPushdown and ReduceElision WMR-safe
```

The following query started hanging (as in , not doing anything ever, with none of the high CPU usage that is usually associated with divergent dataflows). Prior to the commit, the query returned rows. The plan has changed from a differential join to a delta join , and we only hav 27 queries with delta joins in the SLT test suite, none of them WMR as far as I can see.

```
explain WITH MUTUALLY RECURSIVE c1 (f1 INTEGER, f2 INTEGER, f3 INTEGER) AS (
        SELECT *
          FROM (VALUES (0, 0, 0))
     UNION ALL (
                SELECT a1.f1 + 1 AS f1,
                       a1.f2 + 1 AS f2,
                       a1.f3 + 1 AS f3
                  FROM c1 AS a1 ,
                       (
                        SELECT *
                          FROM c1 AS a1
                          LEFT JOIN c1 AS a2 USING (f2)
                         WHERE a1.f1 < 100
                           AND a2.f2 IS NULL
                       ) AS a2
                 WHERE a1 . f1 < 100
               )
       ) SELECT *
  FROM c1;

--- 16875.out	2023-04-13 11:29:16.619724726 +0200
+++ 6875.out	2023-04-13 11:29:16.435720799 +0200
@@ -1,39 +1,37 @@
 Explained Query:
   Return
     Get l0
   With Mutually Recursive
     cte l0 =
       Union
         Project (#3..=#5)
           Map ((#0 + 1), (#1 + 1), (#2 + 1))
             CrossJoin type=differential
               ArrangeBy keys=[[]]
                 Filter (#0 < 100)
                   Get l0
               ArrangeBy keys=[[]]
                 Union
                   Negate
                     Project ()
-                      Join on=(#0 = #1) type=differential
+                      Join on=(eq(#0, #1, #2)) type=delta
                         ArrangeBy keys=[[#0]]
                           Project (#1)
                             Filter (#0 < 100)
                               Get l0
                         ArrangeBy keys=[[#0]]
                           Distinct group_by=[#0]
-                            Project (#0)
-                              Join on=(#0 = #1) type=differential
-                                ArrangeBy keys=[[#0]]
                                   Project (#1)
                                     Filter (#1) IS NOT NULL
                                       Get l0
                                 ArrangeBy keys=[[#0]]
+                          Distinct group_by=[#0]
                                   Project (#1)
                                     Filter (#1) IS NOT NULL
                                       Get l0
                   Project ()
                     Filter (#0 < 100)
                       Get l0
         Constant
           - (0, 0, 0)
```

**Comment by ggevay** [comment]
No, sorry, wait, I ran the wrong query after I added my debug prints... Disregard the above. I'm still investigating.

**Comment by ggevay** [comment]
Still debugging. This is the current state: https://materializeinc.slack.com/archives/CMNT2QSBZ/p1681401292986149

**Comment by ggevay** [comment]
We (mostly Frank) figured out the problem and the solution in the above Slack thread! It's a bug inside Differential's half-join. I'll open a PR tomorrow to Differential.

**Comment by ggevay** [comment]
Fixed by https://github.com/TimelyDataflow/differential-dataflow/pull/386

**Comment by philip-stoev** [comment]
@ggevay I am sorry, the query in question in this ticket still hangs as before, even though my Cargo.lock reports that differential-dataflow is at revision `cc88469a4834faa179725d52e2beb7ab677bdb37`
