### ISSUE TITLE
IO error: lock hold by current process, acquire time 1686932018 acquiring thread 139789160330816: /mzdata/source_data/u46/3/LOCK: No locks available

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19999]
### What version of Materialize are you using?

8550fe6

### What is the issue?

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "IO error: lock hold by current process, acquire time 1686932018 acquiring thread 139789160330816: /mzdata/source_data/u46/3/LOCK: No locks available" }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-057cba75ebdb1f2c8-1/materialize/nightlies/src/rocksdb/src/lib.rs:291:82 
```
https://buildkite.com/materialize/nightlies/builds/2614#_ (also retriggered to see if flaky or actually coming from that change)

I haven't seen these failures before today. They happened in @sploiselle's change fixing another panic: https://github.com/MaterializeInc/materialize/pull/19996
But seem to be unrelated to the change. I'm guessing they are flakes? I didn't see any RocksDB-related changes recently.

ci-regexp: IO error: lock hold by current process, acquire time

**Comment by def-** [comment]
@sploiselle Are you sure this doesn't come from your https://github.com/MaterializeInc/materialize/pull/19310 ? I have tried reproducing this locally, and it reproduces relatively well (`bin/mzcompose --find zippy down && bin/mzcompose --find zippy run default --scenario=KafkaSources --actions=10000 --max-execution-time=55m`). I have compared the state just before your PR (ca3210929be83902557cd4d72d84921baa25bf7b) with the state after your PR (7d1f6e2830c835ed4d953ac7c29e4e157d31a1ef) with a cherry-pick of https://github.com/MaterializeInc/materialize/pull/19996 on top.

I could not reproduce the issue before your change (but often get OoM instead), but could reproduce it easily after it.

**Comment by sploiselle** [comment]
@def- Will pore over my PR to see. The original PR was open for an exceptionally long time so there's a chance of either merge skew or something getting lost during a rebase.

@guswynn Do you have any intuition how a command change like #19310 could result in a lock issue in RocksDB? My hunch is that something got mangled in generalizing the read hold code––does RocksDB use locks to enforce frontiers?

**Comment by guswynn** [comment]
@sploiselle rocksdb has a single process owner of a running instance, so if you shut down a dataflow (with an upsert operator), and start a copy of it before that original one is actually dead, you might get some overlap, and get this panic

**Comment by benesch** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/20033. (The PR description didn't quite get the magic "fixes" syntax right.)

**Comment by def-** [comment]
@sploiselle This is still happening in CI: https://buildkite.com/materialize/nightlies/builds/6470#018dadae-4008-4d79-92a9-15b0400db06c
```
zippy-storaged-1          | thread 'timely:work-0' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0c96fb2bcfbeb04a6-1/materialize/tests/src/storage/src/render/upsert.rs:303:26: called `Result::unwrap()` on an `Err` value: RocksDB(Error { message: "IO error: lock hold by current process, acquire time 1708018430 acquiring thread 281473003661504: /scratch/storage/upsert/u8/0/LOCK: No locks available" })
```
This was on a PR enabling scratch directories explicitly, so maybe it's also related to that? I'm rerunning the test to check.

**Comment by sploiselle** [comment]
@def- Do you mind giving me the steps to repro this with `ALTER CONNECTION`?

**Comment by def-** [comment]
```
bin/mzcompose --find zippy down && bin/mzcompose --find zippy run default --scenario=AlterConnectionWithKafkaSources --actions=10000 --max-execution-time=30m
```
I'm not sure if it's reproducible though, happened on [fed4bb6a48](https://github.com/MaterializeInc/materialize/commit/fed4bb6a483affdf9e5e8e5ee24adb79baec22c2)
([Pull Request #25288](https://github.com/MaterializeInc/materialize/pull/25288))

**Comment by def-** [comment]
This seems to be reproducible and has happened all the time in Nightly after my PR https://github.com/MaterializeInc/materialize/pull/25288 merged. So I'm guessing that PR caused it by enabling scratch directory on clusterd in CI. Maybe I'm misunderstanding something and my PR was actually wrong?

**Comment by benesch** [comment]
> This seems to be reproducible and has happened all the time in Nightly after my PR #25288 merged. So I'm guessing that PR caused it by enabling scratch directory on clusterd in CI. Maybe I'm misunderstanding something and my PR was actually wrong?

I do think that PR has a bug, but I don't think it's related to this issue!

I suspect that `ALTER CONNECTION` on an upsert source just doesn't work today, and we didn't notice before because we weren't exercising that combination of things in CI.

> I assumed that if we dropped the source's tokens that this would release the lock on the RocksDB dir, but that doesn't seem to be the case.
> 
> Either of you have a sense as to what's going on here? Is this just a vanilla race condition? Is there a bug with the shutdown tokens for disk-backed upsert sources?

@sploiselle forgive my unfamiliarity with this part of the codebase, but what is it that causes tokens to drop when a `RunIngestions` command arrives that updates an existing ingestion description?

**Comment by sploiselle** [comment]
I ran the test with this patch which ensured that we dropped the tokens before rendering:

```diff
diff --git a/src/storage/src/render/mod.rs b/src/storage/src/render/mod.rs
index a2b47624f3..0a93092583 100644
--- a/src/storage/src/render/mod.rs
+++ b/src/storage/src/render/mod.rs
@@ -236,6 +236,10 @@ pub fn build_ingestion_dataflow<A: Allocate>(
     let worker_logging = timely_worker.log_register().get("timely");
     let debug_name = primary_source_id.to_string();
     let name = format!("Source dataflow: {debug_name}");
+
+    // Ensure this source's previous tokens are dropped
+    let _ = storage_state.source_tokens.remove(&primary_source_id);
+
     timely_worker.dataflow_core(&name, worker_logging, Box::new(()), |_, root_scope| {
         // Here we need to create two scopes. One timestamped with `()`, which is the root scope,
         // and one timestamped with `mz_repr::Timestamp` which is the final scope of the dataflow.
```

I've also tested a version where I block for 30 seconds if the token previously existed and the same thing occurred.

**Comment by benesch** [comment]
Oh, I see! That code's not yet on main, yeah? I don't think dropping the tokens has any immediate effect. I believe, but am not certain, that you need the main loop (the one that calls `self.timely_worker.step()`) to go through one turn. I'm not even sure that's guaranteed to happen after a single call to step. I think it's likely! I'm just not sure it's guaranteed. Until you call `worker.step()`, timely's not going to notice that the source operators are done and can be cleaned up. 

There are at least two options here. You'll probably want the usual crew (@petrosagg, @aljoscha, @guswynn) to weigh in on which option is best. Possibly there is an even better third option.

1. Rig up some sort of protocol where, when re-rendering a source, you first drop the source tokens, then _wait_ until you observe the drop, and _then_ schedule the new rendering. Sounds kinda complicated, but there's a bunch of infrastructure already for this sort of delayed command scheduling, so maybe there's an easy way to do it.
2. Generate some sort of instance ID when rendering a source. Like, you could probably just stick a UUID in `InternalStorageCommand::CreateIngestionDataflow`, and plumb that into the RocksDB path. That'll guarantee that even if there's a short window where two ingestions are live for the same source ID, they don't conflict on the data directory.

**Comment by petrosagg** [comment]
strong preference for waiting for the previous render to finish before starting the next one. This is effectively what will be happening once the reschedule logic moves to the controller

**Comment by sploiselle** [comment]
Filed #25417 to track this work.

In the meantime, I will put up a PR that disables `ALTER CONNECTION` on connections in use by RocksDB-backed sources.

**Comment by def-** [comment]
This is still happening in Longer Zippy Kafka Parallel Insert, even without any apparent `ALTER CONNECTION`s: https://buildkite.com/materialize/release-qualification/builds/467#018ebe9c-6442-4379-af26-3b496cab809d. All it does is:
```python
class KafkaParallelInsert(Scenario):
    """A Zippy test using simple views over Kafka sources with parallel insertion."""

    def actions_with_weight(self) -> dict[ActionOrFactory, float]:
        return {
            KillClusterd: 5,
            StoragedKill: 5,
            StoragedStart: 5,
            CreateTopicParameterized(): 10,
            CreateSourceParameterized(): 10,
            CreateViewParameterized(expensive_aggregates=False, max_inputs=1): 5,
            ValidateView: 10,
            KafkaInsertParallel: 50,
        }
```

**Comment by guswynn** [comment]
@def- I am not sure, could multiple instances of mz in a zippy scenario shared a scratch dir

**Comment by guswynn** [comment]
I looked more into this, and I think there are definitely 2 separate cases:

- A race when a source is being restarted/errored, where the next instance of the dataflow can fight with the other. Fundamentally shutting down rocksdb and dropping the lock is an asynchronous process; communicated this progress back to the storage controller to pause re-rendering is a non-trivial, and something we'd have to discuss; ill put this on the storage sync agenda
- A race or something weird going on when source are not being restarted; this one I'm way less sure on; is it possible we have overlapping restarting storage clusterd instances (like we use sigterm and not sigkill)?

**Comment by def-** [comment]
> @def- I am not sure, could multiple instances of mz in a zippy scenario shared a scratch dir?

There is only one Materialize running.

> is it possible we have overlapping restarting storage clusterd instances (like we use sigterm and not sigkill)?

The test uses SIGKILL.

**Comment by guswynn** [comment]
I wonder what the delay on a sigkill causing file locks to be dropped is....

Maybe the solution here is a few seconds of retrying opening rocksdb before giving up!

**Comment by def-** [comment]
This occurred again in CI: https://buildkite.com/materialize/nightly/builds/8947#01911d2a-e601-488e-92e4-f1e6ee0c38f2 (see also [CI Failures](https://ci-failures.dev.materialize.com/?key=test-failures&tfFilters=%5B%7B%22id%22%3A%22build_date%22%2C%22value%22%3A%5Bnull%2Cnull%5D%7D%2C%7B%22id%22%3A%22content%22%2C%22value%22%3A%22lock%20hold%20by%20current%20process%22%7D%2C%7B%22id%22%3A%22branch%22%2C%22value%22%3A%22main%22%7D%5D))
