### ISSUE TITLE
Column type unioning does not recurse

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#6750]
Create a Sqllogictest file and copy this in:
```
statement ok
CREATE TABLE t1 (a int not null, b int not null)

statement ok
CREATE TABLE t2 (a int, b int)

statement ok
INSERT INTO t1 values (1, 2)

statement ok
INSERT INTO t2 values (null, null)

query T multiline
EXPLAIN SELECT row(a,b) as record from t1 union select row(a,b) as record from t2
----
EOF
```

Then run the file with argument `-v`. You will get this error:
```
EXPLAIN SELECT row(a,b) as record from t1 union select row(a,b) as record from t2
    PlanFailure:test/sqllogictest/blah2.slt:10:
    db error: ERROR: UNION types record(f1: integer,f2: integer) and record(f1: integer?,f2: integer?) cannot be matched: ERROR: UNION types record(f1: integer,f2: integer) and record(f1: integer?,f2: integer?) cannot be matched
```

Looking at `repr::ColumnType::union`, it seems that the difference in nullability should not prevent unioning. When unioning record-type columns, we need to recurse into the fields of the record to see if the field types line up, ignoring the nullability of the fields.
https://github.com/MaterializeInc/materialize/blob/82ae64f89dfbbb2b441f8084b822a71fbec750d6/src/repr/src/relation.rs#L45

Postgresql handles this case fine:
```
andiwang=# select row(a,b) as record from test union select row(a, b) from test2;
 record 
--------
 (1,2)
 (,)
(2 rows)
```

**Comment by wangandi** [comment]
This issue can cause materialize to crash during the optimization stage, though we have not managed to get a crash to happen outside of the randomized testing framework. https://github.com/MaterializeInc/materialize/pull/6485#issuecomment-836680156

**Comment by prcastro** [comment]
Solved by #6811

**Comment by wangandi** [comment]
Thanks so much!

@philip-stoev Can you test that the crash in the randomized testing framework has gone away? If not, can you file a new issue with whatever is still crashing?
