### ISSUE TITLE
sql: Race condition in test_no_block, fake schema registry server may terminate with unexpected error message

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7107]
### What version of Materialize are you using?

```
1846d4bac7edfd03f92e0927825123825338ca4e
```

### What was the issue?

Sporadic test failures have been observed in buildkite

https://buildkite.com/materialize/tests/builds/18388#cafa9670-90fa-4149-b2db-e78e236c77dd

I was able to reproduce the issue locally and this is the offending statement:

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f67f3485859 in __GI_abort () at abort.c:79
#2  0x0000555d31c06f87 in std::sys::unix::abort_internal () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/mod.rs:237
#3  0x0000555d31bf9666 in std::process::abort () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/process.rs:1784
#4  0x0000555d3128e458 in ore::panic::set_abort_on_panic::{{closure}} (panic_info=0x7f67f23f5358) at /home/pstoev/materialize/src/ore/src/panic.rs:42
#5  0x0000555d31bfe306 in std::panicking::rust_panic_with_hook () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:595
#6  0x0000555d31bfddf7 in std::panicking::begin_panic_handler::{{closure}} () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:495
#7  0x0000555d31bfb69c in std::sys_common::backtrace::__rust_end_short_backtrace () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys_common/backtrace.rs:141
#8  0x0000555d31bfdd89 in rust_begin_unwind () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/panicking.rs:493
#9  0x0000555d31c1f611 in core::panicking::panic_fmt () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/panicking.rs:92
#10 0x0000555d31c1f55d in core::panicking::panic () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/core/src/panicking.rs:50
#11 0x0000555d2c5a4558 in sql::test_no_block () at /home/pstoev/materialize/src/materialized/tests/sql.rs:100
#12 0x0000555d2c6d6a0e in sql::test_no_block::{{closure}} () at /home/pstoev/materialize/src/materialized/tests/sql.rs:37
#13 0x0000555d2c7053be in core::ops::function::FnOnce::call_once () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227
#14 0x0000555d2c7702d3 in core::ops::function::FnOnce::call_once () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227
#15 test::__rust_begin_short_backtrace () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/test/src/lib.rs:557
#16 0x0000555d2c76e991 in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
#17 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:344
#18 std::panicking::try::do_call () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379
#19 std::panicking::try () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343
#20 std::panic::catch_unwind () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431
#21 test::run_test_in_process () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/test/src/lib.rs:579
#22 test::run_test::run_test_inner::{{closure}} () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/test/src/lib.rs:487
#23 0x0000555d2c7462f6 in std::sys_common::backtrace::__rust_begin_short_backtrace () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:125
#24 0x0000555d2c74aa8d in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/mod.rs:474
#25 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:344
#26 std::panicking::try::do_call () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379
#27 std::panicking::try () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343
#28 std::panic::catch_unwind () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431
#29 std::thread::Builder::spawn_unchecked::{{closure}} () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/mod.rs:473
#30 core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227
#31 0x0000555d31c067ca in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
#32 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
#33 std::sys::unix::thread::Thread::new::thread_start () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/thread.rs:71
#34 0x00007f67f37e7609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#35 0x00007f67f3582293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) frame 11
#11 0x0000555d2c5a4558 in sql::test_no_block () at /home/pstoev/materialize/src/materialized/tests/sql.rs:100
100	    assert!(slow_res
(gdb) list
95	
96	    // Verify that the schema registry error was returned to the client, for
97	    // good measure
98	    info!("test_no_block: joining thread");
99	    let slow_res = slow_thread.join().unwrap();
100	    assert!(slow_res
101	        .unwrap_err()
102	        .to_string()
103	        .contains("server error 503"));
104	
```

I added this instrumentation:

```
diff --git a/src/materialized/tests/sql.rs b/src/materialized/tests/sql.rs
index c4f1e6fb5..85118b321 100644
--- a/src/materialized/tests/sql.rs
+++ b/src/materialized/tests/sql.rs
@@ -97,6 +97,7 @@ fn test_no_block() -> Result<(), Box<dyn Error>> {
     // good measure.
     info!("test_no_block: joining thread");
     let slow_res = slow_thread.join().unwrap();
+    info!("test_no_block: {:#?}", slow_res);
     assert!(slow_res
         .unwrap_err()
         .to_string()
```

and so I am getting:

```
2021-06-21T08:12:55.111976Z  INFO sql: test_no_block: Err(
    Error {
        kind: Db,
        cause: Some(
            DbError {
                severity: "ERROR",
                parsed_severity: None,
                code: SqlState
                    EXX000,
                ),
                message: "fetching latest schema for subject \'foo-value\' from registry: transport: error sending request for url (http://localhost:33949/subjects/foo-value/versions/latest): channel closed: error sending request for url (http://localhost:33949/subjects/foo-value/versions/latest): channel closed: channel closed",
                detail: None,
                hint: None,
                position: None,
                where_: None,
                schema: None,
                table: None,
                column: None,
                datatype: None,
                constraint: None,
                file: None,
                line: None,
                routine: None,
            },
        ),
    },
)    
```

In other words, the assertion expects "server error 503" that the test intends to inject, but materialize reports "channel closed: channel closed" instead.

The same structure printed on a successful run looks like this:

```
2021-06-21T08:12:55.438671Z  INFO sql: test_no_block: Err(
    Error {
        kind: Db,
        cause: Some(
            DbError {
                severity: "ERROR",
                parsed_severity: None,
                code: SqlState(
                    EXX000,
                ),
                message: "fetching latest schema for subject \'foo-value\' from registry: server error 503: unable to decode error details",
                detail: None,
                hint: None,
                position: None,
                where_: None,
                schema: None,
                table: None,
                column: None,
                datatype: None,
                constraint: None,
                file: None,
                line: None,
                routine: None,
            },
        ),
    },
)    
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes, run ```target/debug/deps/sql-``` 10 times concurrently by using ```&``` to send each execution to the background. Once they have all completed, the shell will report that 1 or more failed with "Aborted". If you have your ```ulimit -c ulimited``` and kernel core pattern set appropriately, you should see core files.

**Comment by umanwizard** [comment]
https://github.com/seanmonstar/reqwest/issues/1221 possibly related?

**Comment by umanwizard** [comment]
Bumping to P2 on the hypothesis that `reqwest` is giving sporadic failures.

**Comment by umanwizard** [comment]
We believe that this is fixed by https://github.com/MaterializeInc/materialize/pull/7111 , and that `reqwest` was not in fact giving sporadic failures.

@philip-stoev , if you see this again, do please reopen.

**Comment by philip-stoev** [comment]
This is still reproducible as described above after the following commit:

```
commit 3a20f6707e132b4d2366101a4ff4edcd17a362ba (HEAD -> main, origin/main, origin/HEAD)
Author: Brennan Vincent <brennan@materialize.io>
Date:   Mon Jun 21 11:19:59 2021 -0400

    Gracefully shut down TCP connection in cargo test.
```
